column_width = 200
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 2
quote_style = "ForceDouble"
call_parentheses = "Always"
collapse_simple_statement = "ConditionalOnly"

[sort_requires]
enabled = false
